[package]
name = "rwg"
version = "0.0.6"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
crossterm = "0.27.0"
rand = "0.8.5"
ratatui = "0.23.0"
serde = "1.0.189"
serde_json = "1.0.107"
