[package]
name = "rwg"
authors = ["TheLinuxPirate"]
version = "0.0.7"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
rand = "0.8.5"
serde = "1.0.189"
serde_json = "1.0.107"
