#+TITLE: Real World The Game! :: Manual
* Table of contents:
** An introduction:
*** Setting:
**** The Game
** Materials:
*** Why & How To Use These Materials In Game 
** Rules:
*** The Setup:
*** Rent
** The Store: 
*** The Market:
**** Rolling Charts
** Example Introduction:
*** Example Day
-----------------------------------------------------------------------------------------------
* An Introduction 
In "Real World The Game" you experience the game of a lifetime.
There are a couple of things that are going to be explained for the player's knowledge.

** Setting:
You are broke person in New York City (located in Brazil) who owes lots of money to different groups. You will pay off this money by selling 
NFTs (digital images sold by using crypto as its currency) to clients. You have 30 days (17 hours each day), to pay off your debt.

*** The Game:
This game may seem confusing and difficult at first, but this documentation tries its best to help clear that up.

As explained in the setting, the main purpose of the game is to sell NFTs to pay off your debts.

*How Many Debts Do I Have To Pay?*

In total 3, (IRS, Cartel, Rent) once you define the amount of money owed each group, you start a new day to pay the debt off.

*Side Note:* 
The IRS & the Cartel have an immutable total, so once you set the price it cannot increase. Rent is different. 
Your rent's total accumulates higher at the end of each day. More detial about rent in the "Rent" section from "The Setup".

*Cryptocurrency?*

Cryptocurrency (crypto for short) is a currency just like the American Dollar (USD). Cryptocurrencies are a bit different from your average currencies though.
The main differences you need to know before playing this game is that there are different types of crypto that have a different vaule in the conversion to
USD.

*Example:*
| Crypto Type | Crypto Number | Crypto's Value in USD |
|-------+-------+---|
| Bitcoin | 1 | 17,221.10 | 
| Ethereum | 1 | 1,326.84 |
| Litecoin | 1 | 81.33 | 
| Monero | 1 | 159.29 |

Date Recorded: 1/9/23

*Side Note:*
Crypto is constantly changing in value so the value of each coin changes daily!

*Why Use Crypto In Game?*

The reason the game uses crypto is because the thing called an "NFT", which is a digital image that people can buy using said cryptos
to gain ownership of said image. You the player will be creating these images (Named: NFT), to gain money to pay off your debt.

*Player Limit:*

The player limit has no fixed size, well sort of...

This game is intended to not have a player limit, as shows the way this game is structured. The most common way you can play this game is by
playing it by yourself. However is not against the rules nor impossible to add more players to the game. 
Lets say you are playing in a party of four. The main objective is to pay off your debt, whichever player pays off their debt first wins!
-----------------------------------------------------------------------------------------------
* Materials:
- A computer or phone (recommended not required)
- 3 D20 die (or a singular one)
- 2 Six sided die (or a singular one)
- Deck of playing cards
- A document (A google doc / or notepad with paper and pen)

** Why & How To Use These Materials In Game:
You will use the computer or phone to find the conversions of the required cryptocurrencies to USD.

The 3 D20 die will be rolled to find out how much money you owe. (If you only have 1 die you can just reuse the same dice.)

The 2 six sided will determine your NFTs' prices. (If you only have 1 die you can just reuse the same dice.)

The deck of playing cards will be used to accumulate your total rent.

A notepad to write down and keep track of your information.
-----------------------------------------------------------------------------------------------
* Rules:
Each player starts with 3 D20s and a deck of playing cards (faced down). 
The D20 will show how much money you owe to certain companies 
and people which you will have to pay off whilst trying to become rich.

** The Introduction:
Grab 2 of the 3 D20s you have, roll those 2 D20s and calculate the total sum of each number you rolled. 
*Double* the current calculated sum. 
Convert the sum to *Bitcoin*, and that is the total amount you owe to the *IRS.* (Highly recommended to write this down and keep track of it) 

Now roll the last D20 that is left. 
*Triple* the number you rolled, convert that number to *Bitcoin* that is the total amount you owe the *Cartel.*
(Highly recommended to write this down and keep track of it)

Now that you have your total amount for each group (being the Cartel and the IRS) convert each total to USD.

*These are helpful things to search up when you are playing your game:*
- Bitcoin Converter (Bitcoin -> USD)
- Ethereum Converter (Ethereum -> USD)
- Monero Converter (Monero -> USD)
- Litecoin Converter (Litecoin -> USD)

*Example:*

| Die | Number(s) Rolled | Total |
|-------+-------+---|
| 2 D20s | 16 & 18 |  34 x 2 = 68 | 
| 1 D20 |  9 | 27  | 


| Group | Bitcoin | USD |
|-------+-------+-----|
| IRS    | 68 |  1,151,083.60 |
| Cartel | 27 |  457,047.90 |

- Write down the conversion of Bitcoin to USD for the IRS & the Cartel in a document.

You live in New York City located in Brazil, you are in lots of debt & now you have to see how many NFTs you can create & sell in 30 days. 
-----------------------------------------------------------------------------------------------
** Rent
Remove the "Joker" card from the deck of playing cards, shuffle the deck, & grab 3 of the playing cards from the deck. Place those 3 cards upside down.
Now the numbers on the top right & left of the cards are going to be added into a total sum. 
*Special Cards:*

| Card | Value |
|-------+------+|
| Ace | 1 |
| King | 10 |
| Queen | 10 |
| Jack | 10 |

(Joker Cards are not used)

The sum of the 3 cards used, will be the rent you have to pay for your apartment in *Ethereum*. 
Now you owe LOTS of money and you are unemployed!
It's time for the player to create NFTs’ to become rich and pay off their debt!

The player will have *30 days* to pay off their debt!
The player will first have to create NFTs’ and sell them.

The crypto you can set for your NFTs’ to sell include: *Litecoin, & Monero.*
Each turn will count as a singular day so make it count!

On a sample day your options are to create NFTs, price them, sell them, and cash out your crypto, check in with your bank, buy supplies, & more!

On your days you have *17 hours* to create NFTs and sell them.
Once your first day starts you can start creating NFTs.

BUT before you get carried away let's explain the core concepts!

*Bank:* 

The bank is where you will store money and take out money that you need. 
You may also use the bank to pay your rent & debt.

*Store:* 

The store has a limited supply of items on day 1 but expands as the days pass by, use your money wisely!
-----------------------------------------------------------------------------------------------
* The Store:
Your options of buying things include:

| Day Unlocked  | Item Name | Price | Benefit | Supply |
|-------+-------+-----|-----+|------+|--------+|-------+|
| ANY DAY | Red Bull  | 4 USD  | 5 NFTs Buff | Infinite |
| ANY DAY | Monster  | 3 USD  | 3 NFTs Buff | Infinite |
| DAY 2 | Cell Phone  | 150 USD  | Useless Item | Only 1 in supply |
| DAY 4 | IPad  | 500 USD  | Halves NFT Production Time | Only 1 in supply |

Your daily NFT Production limit is set to *10 per day* (without buffs).
Each NFT takes *2 hours* to complete production.

** The Market:
The Market is where you will set up your NFTs to be sold.
You can say that you set up an NFT for sale and state your price. 
After that the game of luck is on your side!

Pull out 2 regular dice and buckle your seat belts!
You are going to roll a die for each NFT you have created and are going to sell on the Market.

Let's say you made 5 NFTs and are going to sell 3 on the Market.
Roll the 1st dice once and mark down the number you got:

*Example Roll: 4*

Roll the 2nd dice and mark down the number you got: 

*Example Roll: 1*

Your 1st roll determines whether someone is going to buy that NFT or not!
If your 1st roll is successful then you will use the 2nd roll according to the next chart!
If your purchase fails then no one buys your NFT and that NFT goes to waste, you CAN NOT reuse NFTs!

** Rolling Charts:

*First Roll:*

(True = Purchase Passed, False = Purchase Failed)

| Roll Number | Status |
|-------+-------+------|
| 1 | False |
| 2 | False |
| 3 | False |
| 4 | True |
| 5 | True |
| 6 | True |

The 2nd roll will determine how they will pay:

*Second Roll:* 

(R = Regular Price, D = Price is Doubled)

| Roll Number | Status |
|-------+-------+------|
| 1 | R |
| 2 | R |
| 3 | R |
| 4 | R |
| 5 | D |
| 6 | D |

We will provide an example day + set up:
Mark is our current player who wants to get The REAL Life experience. Mark will now read the rules and start his journey!
------------------------------------------------------------------------------------------------------------------------------------
* Examples:
** Example Introduction:
- Mark buys a deck of playing cards, 3 D20s, a notepad (recommended), and 2 regular die.
- Mark then grabs 2 of his 3 D20s and rolls them together.
- Mark rolled a 16 and 15; Mark adds these two numbers together and his sum is: 31; 
- Now Mark doubles this sum and he gets: 62. 
- Mark now uses this sum as his Bitcoin total and converts the Bitcoin total to USD.
- Mark puts 62 as the number in the Bitcoin section and the total money owed is the USD output that he owes to the:

*IRS: $1,255,859.60.*

- Mark now uses the 1 D20 that is left and he rolls a 14. 
- Mark triples this number to receive: 42. 
- Mark now uses this sum as his Bitcoin total and converts the Bitcoin total to USD. 
- Mark puts 42 as the number in the Bitcoin section and the total money is the USD output that he owes to the Cartel: $850,743.60.
- Mark then writes down the Bitcoin amount and the USD amount he owes to each group. 

Before Mark can finish his introduction he now has to worry about his apartment’s rent!

- Mark will grab 3 cards from the deck of cards and place them face down.
- Mark will then reveal all of the cards and calculate the total sum of each card.
- Mark got a: *2, 3, and a 10!*
- Mark’s total sum is: *15!*
- Mark now converts his 15 to Ethereum then USD just like how he did with Bitcoin!

*Introduction Rent: $22,539.45.*

Mark has now finished the introduction!

Now it is time for Mark to start his 1st day!
------------------------------------------------------------------------------------------------------------------------------------
** Example Day:

Each player starts with *50$* in their bank.


Each day starts at *07:00*!


- Mark spends *4 USD* and buys a Red Bull which gives him a *1 day* buff to make _5 more_ NFTs.

- Mark subtracts *4 USD* from his bank total!

- Mark creates *4 NFTs*, spending *8 hours* of his time in total!

- It is now 14:00!

- Mark puts *1* of his *4 NFTs* on The Market.

- The 1st NFT: *15 Litecoin*.

- Mark will now roll for his NFT!

- Mark got a *4* on his *1st roll*!

- Mark got a *3* on his *2nd roll*!

- Mark’s 1st NFT passed but didn’t double his price!

- Mark’s 1st NFT value: *15 Litecoin/818.25 USD*

- Mark can now bank his earnings!

- Mark adds *818.25 USD* to his bank account!

- Mark’s total is now *864.25 USD*.

- Mark chooses to end his day!

- Mark did not pay any of his debt today!

- Mark now has to draw for rent again!

- Mark got a: *6, 10, and another 10*!

- Mark’s total sum is: *26*.

(Remember that rent is in “Ethereum”)

- *New Rent: $39,157.82!*

- Mark then adds up the rent total.

- *Rent Total: $61,697.27!*
  
